from tkinter import *
from tkinter import messagebox
def INSERT(event):
    if(event.char=='\b'):Equation.set((Equation.get())[0:len(Equation.get())-1])
    elif(event.char=="\N{CARRIAGE RETURN}" or event.char=='='):
        Ans()
    else:Equation.set(Equation.get()+event.char)
def ONE():Equation.set(Equation.get()+"1")
def TWO():Equation.set(Equation.get()+"2")
def THREE():Equation.set(Equation.get()+"3")
def FOUR():Equation.set(Equation.get()+"4")
def FIVE():Equation.set(Equation.get()+"5")
def SIX():Equation.set(Equation.get()+"6")
def SEVEN():Equation.set(Equation.get()+"7")
def EIGHT():Equation.set(Equation.get()+"8")
def NINE():Equation.set(Equation.get()+"9")
def ZERO():Equation.set(Equation.get()+"0")
def ADD():Equation.set(Equation.get()+"+")
def SUB():Equation.set(Equation.get()+"-")
def MUL():Equation.set(Equation.get()+"*")
def DIV():Equation.set(Equation.get()+"/")
def LBRACKET():Equation.set(Equation.get()+"(")
def RBRACKET():Equation.set(Equation.get()+")")
def POINT():Equation.set(Equation.get()+".")
def AC():Equation.set("")
def C():Equation.set((Equation.get())[0:len(Equation.get())-1])
def Ans():
    try:Equation.set(eval(Equation.get()))
    except:
        messagebox.showerror(title="Error",message="Entered data is not an Equation")
Calc=Tk()
Calc.config(bg="gray17")
Calc.title("Basic Calculator by Kunal Upadhyay")
Equation=StringVar()
Label(textvariable=Equation,bg="gray10",fg="white",font="Ariel 25 bold",height=2,anchor="se").pack(fill='x')
Calc.bind('<Key>',INSERT)
F=Frame(Calc,bg="gray17")
F.pack()
Button(F,text="(",fg="white",bg="gray17",command=LBRACKET,borderwidth=0,padx=20,pady=20).grid(row=0,column=0)
Button(F,text=")",fg="white",bg="gray17",command=RBRACKET,borderwidth=0,padx=20,pady=20).grid(row=0,column=1)
Button(F,text=".",fg="white",bg="gray17",command=POINT,borderwidth=0,padx=20,pady=20).grid(row=4,column=2)
Button(F,text="7",fg="white",bg="gray17",command=SEVEN,borderwidth=0,padx=20,pady=20,activebackground="red").grid(row = 1,column = 0)
Button(F,text="8",fg="white",bg="gray17",command=EIGHT,borderwidth=0,padx=20,pady=20,activebackground="red").grid(row = 1,column = 1)
Button(F,text="9",fg="white",bg="gray17",command=NINE,borderwidth=0,padx=20,pady=20,activebackground="red").grid(row = 1,column = 2)
Button(F,text="4",fg="white",bg="gray17",command=FOUR,borderwidth=0,padx=20,pady=20,activebackground="red").grid(row = 2,column = 0)
Button(F,text="5",fg="white",bg="gray17",command=FIVE,borderwidth=0,padx=20,pady=20,activebackground="red").grid(row = 2,column = 1)
Button(F,text="6",fg="white",bg="gray17",command=SIX,borderwidth=0,padx=20,pady=20,activebackground="red").grid(row = 2,column = 2)
Button(F,text="1",fg="white",bg="gray17",command=ONE,borderwidth=0,padx=20,pady=20,activebackground="red").grid(row = 3,column = 0)
Button(F,text="2",fg="white",bg="gray17",command=TWO,borderwidth=0,padx=20,pady=20,activebackground="red").grid(row = 3,column = 1)
Button(F,text="3",fg="white",bg="gray17",command=THREE,borderwidth=0,padx=20,pady=20,activebackground="red").grid(row = 3,column = 2)
Button(F,text="0",fg="white",bg="gray17",command=ZERO,borderwidth=0,padx=20,pady=20,activebackground="red").grid(row = 4,column = 0)
Button(F,text="=",fg="white",bg="gray17",command=Ans,borderwidth=0,padx=20,pady=20).grid(row=4,column=1)
Button(F,text="+",fg="white",bg="gray17",command=ADD,borderwidth=0,padx=20,pady=20).grid(row = 1,column = 3)
Button(F,text="-",fg="white",bg="gray17",command=SUB,borderwidth=0,padx=20,pady=20).grid(row = 2,column = 3)
Button(F,text="*",fg="white",bg="gray17",command=MUL,borderwidth=0,padx=20,pady=20).grid(row = 3,column = 3)
Button(F,text="/",fg="white",bg="gray17",command=DIV,borderwidth=0,padx=20,pady=20).grid(row = 4,column = 3)
Button(F,text="AC",fg="white",bg="gray17",command=AC,borderwidth=0,padx=17,pady=20).grid(row = 0,column = 2)
Button(F,text="C",fg="white",bg="gray17",command=C,borderwidth=0,padx=20,pady=20).grid(row = 0,column = 3)
Calc.mainloop()
